import type { Metadata } from "next";
import "./style/globals.css";
import "./style/footer.css";
import { CompanyModel } from "@/_domain/models/company.model";
import { getCompanyData } from "@/_domain/services/company.services";
import Nav from "@/common/components/nav/Nav";
import ScrollSmootherProvider from "@/common/lib/gsap/ScrollSmootherProvider";
import { serialize } from "@/common/utils/helper-serialize";
import { Inter } from 'next/font/google'
import Footer from "@/common/components/footer/Footer";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-primary', // opcional, útil si usas CSS variables
  display: 'swap',
})

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const rawData = await getCompanyData();
	const data = new CompanyModel(rawData);

	return (
		<html lang="es" className={inter.variable}>
			<body suppressHydrationWarning>
				<Nav companyData={serialize(data)} />
				<ScrollSmootherProvider>
					{children}
					<Footer />
				</ScrollSmootherProvider>
			</body>
		</html>
	);
}
