import type { Metadata } from "next";
import "./style/globals.css";
import { CompanyModel } from "@/_domain/models/company.model";
import { getCompanyData } from "@/_domain/services/company.services";
import Nav from "@/common/components/nav/Nav";
import ScrollSmootherProvider from "@/common/lib/gsap/ScrollSmootherProvider";
import { serialize } from "@/common/utils/helper-serialize";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const rawData = await getCompanyData();
	const data = new CompanyModel(rawData);

	return (
		<html lang="en">
			<body>
				<Nav companyData={serialize(data)} />
				<ScrollSmootherProvider>{children}</ScrollSmootherProvider>
			</body>
		</html>
	);
}
